org: johnldev
# app: ts-example
service: typescript
useDotenv: true
frameworkVersion: '2'

plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb-local 
  - serverless-offline
  - serverless-webpack

custom:
  funcDir: src/4-framework/functions
  dynamodb:
    stages: 
      - ${self:provider.stage}
    start:
      host: ${self:provider.environment.LOCALSTACK_HOST}
      port: ${self:provider.environment.LOCALSTACK_PORT}
      migrate: true
      noStart: true
      seed: true
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceInclude: 
        - mysql2

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  stage: ${opt:stage, "${env:stage, 'dev'}"}
  region: ${opt:region, "${env:region, 'us-east-1'}"}
  timeout: 28
  memorySize: 512
  environment: 
    LOCALSTACK_HOST: ${env:LOCALSTACK_HOST, "localhost"}
    LOCALSTACK_PORT: ${env:LOCALSTACK_PORT, "4566"}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:CreateTable
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:ListStreams
          Resource: 'arn:aws:dynamodb:${self:provider.region}:*:*'
  vpc:
    securityGroupIds:
      - sg-01c5b51c6ac07e81d
    subnetIds:
      - subnet-05be106cc976db75c
      - subnet-07068b570660d194a
      - subnet-0c3b56549c93364ff
      - subnet-0e9f51f1cb27eab50
      - subnet-075e51883375ab8ce
      - subnet-0167b640074c77fad
        

functions:
  CreateUser:
    handler: ${self:custom.funcDir}/user/CreateUserFunction.handler
    events:
      - http:
          path: /user
          method: post
          cors: 
            origin: '*'
  DynamoTest:
    handler: ${self:custom.funcDir}/DynamoTest.handler
    events:
      - http:
          path: /Dynamo
          method: post
          cors: 
            origin: '*'

resources:
  - ${file("./devops/resources/dynamo.yml")}


package:
  individually: true
  excludeDevDependencies: true