# org: johnldev
# app: ts-example
service: typescript
useDotenv: true
frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  funcDir: src/4-framework/functions
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceInclude: 
        - mysql2

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  stage: ${opt:stage, "${env:stage, 'dev'}"}
  region: ${opt:region, "${env:region, 'us-east-1'}"}
  timeout: 28
  memorySize: 512
  environment:
    AURORA_HOST: ${env:AURORA_HOST, ssm:/fgts/infra/aurora/host}
    AURORA_PORT: ${env:AURORA_PORT, ssm:/fgts/infra/aurora/port}
    AURORA_USERNAME: ${env:AURORA_USERNAME, ssm:/fgts/infra/aurora/username}
    AURORA_PASSWORD: ${env:AURORA_PASSWORD, ssm:/fgts/infra/aurora/password}
    AURORA_DB_NAME: ${env:AURORA_DB_NAME, ssm:/fgts/infra/aurora/db}

        

functions:
   - ${file(${self:custom.funcDir}/user/user.yml)}

   
package:
  individually: true
  excludeDevDependencies: true