service: typescript
frameworkVersion: '2'

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'




functions:
  api:
    handler: src/app.handler
    events:
      - httpApi: '*'


package:
  individually: true
  excludeDevDependencies: true