# This is a basic workflow to help you get started with Actions

name: FEATURE

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn install

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Test Coverage
        run: yarn test:coverage

      - uses: vebr/jest-lcov-reporter@v0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info  

      # - uses: artiomtr/jest-coverage-report-action@v1.0
      #   name: Test Coverage
      #   with:
      #       github_token: ${{ secrets.GITHUB_TOKEN }}
      #       threshold: 20 # optional parameter
      #       test_script: npm run test:coverage